import { describe, expect, it } from 'vitest';
import { registerMachine, updateMachineTelemetry, canAssignMachine, assignMachineToJob, markMachineOffline, summarizeRegistry } from '../src/fleet/registry.js';
import { createWorkOrder, allowedWorkOrderActions, transitionWorkOrder } from '../src/jobs/work-order.js';
import { normalizeTelemetrySnapshot } from '../src/telemetry/snapshot.js';
import { deriveTelemetryRef } from '../src/telemetry/evidence.js';
import { createWorkEvidenceBundle, summarizeEvidenceBundle } from '../src/proofs/evidence-bundle.js';

const machineInput = { machineId: 'rover-22', role: 'rover' as const, walletAddress: '0x1111111111111111111111111111111111111111', operatorId: 'ops', capabilities: ['mapping' as const, 'audit_capture' as const], fleetId: 'campus-fleet', siteId: 'north-yard' };
const orderInput = { workOrderId: 'wo-yard-map-22', requirement: { capabilities: ['mapping' as const], telemetryRequired: true, proofRequired: true }, settlement: { chain: 'solana' as const, amount: '0.75', asset: 'SOL', recipient: '11111111111111111111111111111111' }, machineId: 'rover-22' };

it('registers and summarizes public-safe fleet entries', () => { const entry = registerMachine(machineInput, '2026-07-14T00:00:00.000Z'); const updated = updateMachineTelemetry(entry, { telemetryRef: 'telemetry:rover-22:1', batteryPct: 82, health: 'nominal' }); expect(updated.fleetId).toBe('campus-fleet'); expect(summarizeRegistry([updated]).available).toEqual(['rover-22']); });
it('gates assignment by status, battery, health, and capabilities', () => { const entry = updateMachineTelemetry(registerMachine(machineInput), { telemetryRef: 't', batteryPct: 8, health: 'nominal' }); expect(canAssignMachine(entry, { jobId: 'job-1', requiredCapabilities: ['mapping'] }).ok).toBe(false); expect(canAssignMachine(markMachineOffline(entry), { jobId: 'job-1', requiredCapabilities: ['mapping'] }).reasons.join(' ')).toContain('offline'); });
it('assigns a capable idle machine to a job', () => { const entry = updateMachineTelemetry(registerMachine(machineInput), { telemetryRef: 't', batteryPct: 80, health: 'nominal' }); const assigned = assignMachineToJob(entry, { jobId: 'job-1', requiredCapabilities: ['mapping'] }); expect(assigned.status).toBe('assigned'); expect(assigned.activeJobId).toBe('job-1'); });
it('rejects assignment when required capability is absent', () => { const entry = updateMachineTelemetry(registerMachine(machineInput), { telemetryRef: 't', batteryPct: 80, health: 'nominal' }); expect(() => assignMachineToJob(entry, { jobId: 'job-2', requiredCapabilities: ['delivery'] })).toThrow(/missing required capability/); });
it('creates work orders and exposes allowed next actions', () => { const order = createWorkOrder(orderInput, '2026-07-14T01:00:00.000Z'); expect(order.stage).toBe('queued'); expect(allowedWorkOrderActions(order)).toEqual(['assigned','cancelled']); });
it('requires telemetry and proof before proof-submitted stage', () => { const order = transitionWorkOrder(createWorkOrder(orderInput), 'assigned', { machineId: 'rover-22' }); const preparing = transitionWorkOrder(order, 'preparing'); const working = transitionWorkOrder(preparing, 'working'); expect(() => transitionWorkOrder(working, 'proof_submitted')).toThrow(/telemetry reference required/); });
it('transitions work order through proof and settlement gates', () => { const working = transitionWorkOrder(transitionWorkOrder(transitionWorkOrder(createWorkOrder(orderInput), 'assigned'), 'preparing'), 'working'); const proofed = transitionWorkOrder(working, 'proof_submitted', { telemetryRef: 'telemetry_1', proofId: 'proof_1' }); const settled = transitionWorkOrder(proofed, 'settled', { settlementIntentId: 'intent_1' }); expect(settled.stage).toBe('settled'); });
it('derives stable telemetry references from normalized snapshots', () => { const snap = normalizeTelemetrySnapshot({ machineId: 'rover-22', observedAt: '2026-07-14T01:02:00Z', batteryPct: 78, health: 'nominal', pose: { x: 1, y: 2, yawDeg: 90 } }); expect(deriveTelemetryRef(snap)).toEqual(deriveTelemetryRef(snap)); });
it('summarizes work evidence bundles without raw telemetry or media', () => { const bundle = createWorkEvidenceBundle({ bundleId: 'bundle-1', machineId: 'rover-22', workOrderId: 'wo-yard-map-22', sessionId: 'session-1', chain: 'solana', telemetryRef: 'telemetry_1', settlementIntentId: 'intent_1', expectation: { amount: '0.75' }, resultRef: 'result:map:sha256' }); expect(summarizeEvidenceBundle(bundle)).toMatchObject({ bundleId: 'bundle-1', hasResult: true, hasMedia: false }); });
