import { describe, expect, it } from 'vitest';
import { createRegistryEntry, machineHasCapabilities } from '../src/machines/identity.js';
import { transitionMachineStatus as transitionStatus } from '../src/machines/status.js';
import { createMachineJob, transitionJob } from '../src/jobs/lifecycle.js';
import { evaluateMachineJobPolicy } from '../src/jobs/policy.js';
import { normalizeTelemetrySnapshot } from '../src/telemetry/snapshot.js';
import { createMachineWorkProof, linkReceiptToWorkProof } from '../src/proofs/work-proof.js';

const machine = () => createRegistryEntry({ machineId: 'robot-arm-17', role: 'robot_arm', walletAddress: '0x1111111111111111111111111111111111111111', operatorId: 'ops-alpha', capabilities: ['pick_place', 'audit_capture'] }, '2026-07-14T00:00:00.000Z');
const job = () => createMachineJob({ jobId: 'job-pallet-44', machineId: 'robot-arm-17', requiredCapabilities: ['pick_place'], chain: 'solana', settlementAmount: '1.25', settlementAsset: 'SOL', recipient: '11111111111111111111111111111111' }, '2026-07-14T00:01:00.000Z');

it('validates machine capability descriptors', () => { const entry = machine(); expect(entry.status).toBe('idle'); expect(machineHasCapabilities(entry, ['pick_place'])).toBe(true); });
it('rejects invalid machine roles and capabilities', () => { expect(() => createRegistryEntry({ machineId: 'x', role: 'forklift' as never, walletAddress: 'w', operatorId: 'o', capabilities: ['pick_place'] })).toThrow(/invalid machine id|invalid machine role/); expect(() => createRegistryEntry({ machineId: 'robot-arm-17', role: 'robot_arm', walletAddress: 'w', operatorId: 'o', capabilities: ['teleport' as never] })).toThrow(/invalid machine capability/); });
it('transitions machine runtime status through assigned and working states', () => { const assigned = transitionStatus(machine(), 'assigned', '2026-07-14T00:02:00.000Z'); const working = transitionStatus(assigned, 'working', '2026-07-14T00:03:00.000Z'); expect(working.status).toBe('working'); });
it('rejects invalid machine status transition', () => { expect(() => transitionStatus(machine(), 'settled' as never)).toThrow(/invalid machine status transition/); });
it('creates and transitions a machine job lifecycle', () => { const created = job(); const assigned = transitionJob(created, 'assigned'); const running = transitionJob(assigned, 'running'); const proofed = transitionJob(running, 'proof_submitted', { proofId: 'proof-1' }); const settled = transitionJob(proofed, 'settled'); expect(settled.status).toBe('settled'); });
it('rejects job settlement before proof submission', () => { expect(() => transitionJob(job(), 'settled')).toThrow(/invalid job transition/); });
it('normalizes telemetry and rejects invalid ranges', () => { const snapshot = normalizeTelemetrySnapshot({ machineId: 'robot-arm-17', observedAt: '2026-07-14T00:02:00Z', batteryPct: 88, health: 'nominal', signalPct: 90, progressPct: 25 }); expect(snapshot.observedAt).toBe('2026-07-14T00:02:00.000Z'); expect(() => normalizeTelemetrySnapshot({ machineId: 'robot-arm-17', observedAt: '2026-07-14T00:02:00Z', batteryPct: 120, health: 'nominal' })).toThrow(/batteryPct/); });
it('accepts and rejects machine job policy decisions with reasons', () => { const snap = normalizeTelemetrySnapshot({ machineId: 'robot-arm-17', observedAt: '2026-07-14T00:02:00Z', batteryPct: 80, health: 'nominal' }); expect(evaluateMachineJobPolicy(machine(), job(), snap, { policyId: 'p', allowedChains: ['solana'], maxAmount: '2', minBatteryPct: 20 }, new Date('2026-07-14T00:03:00Z')).accepted).toBe(true); const rejected = evaluateMachineJobPolicy(machine(), { ...job(), requiredCapabilities: ['mapping'] }, { ...snap, batteryPct: 5 }, { policyId: 'p', allowedChains: ['solana'], maxAmount: '0.1', minBatteryPct: 20 }, new Date('2026-07-14T00:03:00Z')); expect(rejected.accepted).toBe(false); expect(rejected.reasons.length).toBeGreaterThanOrEqual(3); });
it('links machine work proof to receipt expectations', () => { const proof = createMachineWorkProof({ machineId: 'robot-arm-17', jobId: 'job-pallet-44', sessionId: 'session-1', chain: 'solana', settlementIntentId: 'intent-1', telemetryRef: 'telemetry-1', expectation: { amount: '1.25', machineId: 'robot-arm-17' } }, '2026-07-14T00:04:00Z'); expect(linkReceiptToWorkProof(proof, 'proof-receipt-1').receiptId).toBe('proof-receipt-1'); });
