import type { RuntimeChain } from '../adapters/shared/types.js';
import type { MachineCapability } from '../machines/identity.js';
import { assertPositiveDecimalAmount } from '../settlement/amounts.js';
export type MachineJobStatus = 'created' | 'assigned' | 'running' | 'proof_submitted' | 'settled' | 'cancelled' | 'failed';
export interface MachineJob { jobId: string; machineId: string; requiredCapabilities: MachineCapability[]; status: MachineJobStatus; chain: RuntimeChain; settlementAmount: string; settlementAsset?: string | undefined; recipient: string; createdAt: string; updatedAt: string; previousJobId?: string | undefined; telemetryRef?: string | undefined; settlementIntentId?: string | undefined; proofId?: string | undefined; }
const transitions: Record<MachineJobStatus, MachineJobStatus[]> = { created: ['assigned', 'cancelled'], assigned: ['running', 'cancelled', 'failed'], running: ['proof_submitted', 'failed'], proof_submitted: ['settled', 'failed'], settled: [], cancelled: [], failed: [] };
export function createMachineJob(input: Omit<MachineJob, 'status' | 'createdAt' | 'updatedAt'>, now = new Date().toISOString()): MachineJob { if (!/^[a-z0-9][a-z0-9._:-]{2,80}$/i.test(input.jobId)) throw new Error('invalid job id'); if (!input.requiredCapabilities.length) throw new Error('job requires at least one capability'); try { assertPositiveDecimalAmount(input.settlementAmount, input.chain === 'solana' ? 9 : 18); } catch { throw new Error('invalid settlement amount'); } return { ...input, status: 'created', createdAt: now, updatedAt: now }; }
export function canTransitionJob(from: MachineJobStatus, to: MachineJobStatus): boolean { return transitions[from]?.includes(to) ?? false; }
export function transitionJob(job: MachineJob, to: MachineJobStatus, patch: Partial<Pick<MachineJob, 'settlementIntentId' | 'proofId' | 'telemetryRef'>> = {}, now = new Date().toISOString()): MachineJob { if (!canTransitionJob(job.status, to)) throw new Error(`invalid job transition ${job.status} -> ${to}`); if (to === 'proof_submitted' && !patch.proofId && !job.proofId) throw new Error('proof id required before proof submission'); if (to === 'settled' && !job.proofId) throw new Error('proof required before settlement'); return { ...job, ...patch, status: to, updatedAt: now }; }
