import type { RuntimeChain } from '../adapters/shared/types.js';
import type { MachineCapability } from '../machines/identity.js';
export type WorkOrderStage = 'queued' | 'assigned' | 'preparing' | 'working' | 'proof_submitted' | 'settled' | 'failed' | 'cancelled';
export interface WorkOrderRequirement { capabilities: MachineCapability[]; telemetryRequired?: boolean | undefined; proofRequired?: boolean | undefined; expectedOutputs?: string[] | undefined; }
export interface SettlementTerms { chain: RuntimeChain; amount: string; asset: string; recipient: string; }
export interface MachineWorkOrder { workOrderId: string; machineId?: string | undefined; stage: WorkOrderStage; requirement: WorkOrderRequirement; settlement: SettlementTerms; createdAt: string; updatedAt: string; telemetryRef?: string | undefined; proofId?: string | undefined; settlementIntentId?: string | undefined; resultRef?: string | undefined; }
const next: Record<WorkOrderStage, WorkOrderStage[]> = { queued: ['assigned','cancelled'], assigned: ['preparing','cancelled','failed'], preparing: ['working','failed','cancelled'], working: ['proof_submitted','failed'], proof_submitted: ['settled','failed'], settled: [], failed: [], cancelled: [] };
export function createWorkOrder(input: Omit<MachineWorkOrder, 'stage' | 'createdAt' | 'updatedAt'>, now = new Date().toISOString()): MachineWorkOrder { if (!/^[a-z0-9][a-z0-9._:-]{2,90}$/i.test(input.workOrderId)) throw new Error('invalid work order id'); if (!input.requirement.capabilities.length) throw new Error('work order requires capabilities'); return { ...input, stage: 'queued', createdAt: now, updatedAt: now }; }
export function allowedWorkOrderActions(order: MachineWorkOrder): WorkOrderStage[] { return [...next[order.stage]]; }
export function validateWorkOrderRequirements(order: MachineWorkOrder): string[] { const reasons: string[] = []; if (order.requirement.telemetryRequired && !order.telemetryRef) reasons.push('telemetry reference required'); if (order.requirement.proofRequired && !order.proofId) reasons.push('proof required'); if (order.stage === 'settled' && !order.settlementIntentId) reasons.push('settlement intent required'); return reasons; }
export function transitionWorkOrder(order: MachineWorkOrder, to: WorkOrderStage, patch: Partial<Pick<MachineWorkOrder, 'machineId' | 'telemetryRef' | 'proofId' | 'settlementIntentId' | 'resultRef'>> = {}, now = new Date().toISOString()): MachineWorkOrder { if (!next[order.stage].includes(to)) throw new Error(`invalid work order transition ${order.stage} -> ${to}`); const candidate = { ...order, ...patch, stage: to, updatedAt: now }; const missing = validateWorkOrderRequirements(candidate); if ((to === 'proof_submitted' || to === 'settled') && missing.length) throw new Error(missing.join('; ')); return candidate; }
