import type { MachineCapability, MachineIdentity, MachineRegistryEntry } from '../machines/identity.js';
import { createRegistryEntry, machineHasCapabilities, validateMachineIdentity } from '../machines/identity.js';
import type { MachineRuntimeStatus } from '../machines/status.js';
import { transitionMachineStatus } from '../machines/status.js';
import type { MachineJob } from '../jobs/lifecycle.js';
export interface FleetRegistryEntry extends MachineRegistryEntry { fleetId?: string | undefined; siteId?: string | undefined; lastTelemetryRef?: string | undefined; batteryPct?: number | undefined; health?: 'nominal' | 'degraded' | 'faulted' | 'offline' | undefined; activeJobId?: string | undefined; }
export interface FleetRegistrySummary { total: number; byStatus: Record<string, number>; byRole: Record<string, number>; available: string[]; faulted: string[]; }
export function registerMachine(input: MachineIdentity & { fleetId?: string; siteId?: string }, now = new Date().toISOString()): FleetRegistryEntry { const base = createRegistryEntry(validateMachineIdentity(input), now); return { ...base, fleetId: input.fleetId, siteId: input.siteId }; }
export function updateMachineTelemetry(entry: FleetRegistryEntry, patch: { telemetryRef: string; batteryPct?: number; health?: FleetRegistryEntry['health'] }, now = new Date().toISOString()): FleetRegistryEntry { if (!patch.telemetryRef) throw new Error('telemetry reference required'); if (patch.batteryPct !== undefined && (patch.batteryPct < 0 || patch.batteryPct > 100)) throw new Error('batteryPct must be 0-100'); return { ...entry, lastTelemetryRef: patch.telemetryRef, batteryPct: patch.batteryPct ?? entry.batteryPct, health: patch.health ?? entry.health, updatedAt: now }; }
export function canAssignMachine(entry: FleetRegistryEntry, job: Pick<MachineJob, 'jobId' | 'requiredCapabilities'>, minBatteryPct = 15): { ok: boolean; reasons: string[] } { const reasons: string[] = []; if (!['idle','completed'].includes(entry.status)) reasons.push(`machine status ${entry.status} is not assignable`); if (entry.health === 'faulted' || entry.health === 'offline') reasons.push(`machine health ${entry.health}`); if ((entry.batteryPct ?? 100) < minBatteryPct) reasons.push('battery below assignment threshold'); if (!machineHasCapabilities(entry, job.requiredCapabilities as MachineCapability[])) reasons.push('machine missing required capability'); if (!job.jobId) reasons.push('job id required'); return { ok: reasons.length === 0, reasons }; }
export function assignMachineToJob(entry: FleetRegistryEntry, job: Pick<MachineJob, 'jobId' | 'requiredCapabilities'>, now = new Date().toISOString()): FleetRegistryEntry { const decision = canAssignMachine(entry, job); if (!decision.ok) throw new Error(decision.reasons.join('; ')); return { ...transitionMachineStatus(entry, 'assigned', now), activeJobId: job.jobId }; }
export function markMachineAvailable(entry: FleetRegistryEntry, now = new Date().toISOString()): FleetRegistryEntry { const status: MachineRuntimeStatus = entry.status === 'offline' || entry.status === 'faulted' ? 'idle' : entry.status === 'completed' ? 'idle' : entry.status; return { ...entry, status, activeJobId: undefined, updatedAt: now }; }
export function markMachineOffline(entry: FleetRegistryEntry, reason = 'offline', now = new Date().toISOString()): FleetRegistryEntry { return { ...entry, status: 'offline', health: 'offline', activeJobId: undefined, updatedAt: now, metadata: { ...entry.metadata, offlineReason: reason } }; }
export function summarizeRegistry(entries: FleetRegistryEntry[]): FleetRegistrySummary { const byStatus: Record<string, number> = {}; const byRole: Record<string, number> = {}; for (const entry of entries) { byStatus[entry.status] = (byStatus[entry.status] ?? 0) + 1; byRole[entry.role] = (byRole[entry.role] ?? 0) + 1; } return { total: entries.length, byStatus, byRole, available: entries.filter((e) => e.status === 'idle' && e.health !== 'faulted' && e.health !== 'offline').map((e) => e.machineId), faulted: entries.filter((e) => e.status === 'faulted' || e.health === 'faulted').map((e) => e.machineId) }; }
