/**
 * Runtime 8 shared visual language.
 *
 * Public pages consume the semantic CSS variables directly. Machine Console
 * maps its existing `--mc-*` API to these values so its component structure
 * remains stable while both experiences share one palette and scale.
 */
export const sharedTheme = {
  color: {
    background: '#070908',
    surface: '#0d110f',
    surfaceElevated: '#111713',
    surfaceOverlay: '#151b17',
    surfaceHover: '#182019',
    surfaceActive: '#202a22',
    border: 'rgba(226, 240, 220, 0.13)',
    borderStrong: 'rgba(226, 240, 220, 0.24)',
    foreground: '#f4f2eb',
    muted: '#a8aaa2',
    mutedSubtle: '#6f746d',
    disabled: '#494e48',
    accent: '#c9f36b',
    accentHover: '#d8ff83',
    accentForeground: '#071006',
    accentMuted: 'rgba(201, 243, 107, 0.09)',
    accentBorder: 'rgba(201, 243, 107, 0.32)',
    success: '#75d99a',
    successMuted: 'rgba(117, 217, 154, 0.08)',
    successBorder: 'rgba(117, 217, 154, 0.28)',
    info: '#7ec8b4',
    infoMuted: 'rgba(126, 200, 180, 0.08)',
    infoBorder: 'rgba(126, 200, 180, 0.28)',
    warning: '#e3b15a',
    warningMuted: 'rgba(227, 177, 90, 0.08)',
    warningBorder: 'rgba(227, 177, 90, 0.30)',
    neutral: '#8b8f88',
    error: '#e46f62',
    errorMuted: 'rgba(228, 111, 98, 0.09)',
    errorBorder: 'rgba(228, 111, 98, 0.30)',
    offline: '#676c66',
  },
  font: {
    sans: 'Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    mono: '"SFMono-Regular", "Cascadia Code", "Roboto Mono", Consolas, monospace',
  },
  radius: { sm: '3px', md: '5px', lg: '8px', xl: '12px', pill: '999px' },
  shadow: {
    card: '0 1px 2px rgba(0, 0, 0, 0.32)',
    overlay: '0 22px 60px rgba(0, 0, 0, 0.52)',
    focus: '0 0 0 3px rgba(201, 243, 107, 0.20)',
  },
  motion: { fast: '140ms ease', standard: '200ms ease' },
  spacing: { 1: '4px', 2: '8px', 3: '12px', 4: '16px', 5: '24px', 6: '32px', 7: '48px', 8: '64px' },
} as const;

export function sharedThemeCssVars(): string {
  const { color, font, radius, shadow, motion, spacing } = sharedTheme;
  return [
    `  --background: ${color.background};`,
    `  --surface: ${color.surface};`,
    `  --surface-elevated: ${color.surfaceElevated};`,
    `  --surface-overlay: ${color.surfaceOverlay};`,
    `  --surface-hover: ${color.surfaceHover};`,
    `  --surface-active: ${color.surfaceActive};`,
    `  --border: ${color.border};`,
    `  --border-strong: ${color.borderStrong};`,
    `  --foreground: ${color.foreground};`,
    `  --muted: ${color.muted};`,
    `  --muted-subtle: ${color.mutedSubtle};`,
    `  --disabled: ${color.disabled};`,
    `  --accent: ${color.accent};`,
    `  --accent-hover: ${color.accentHover};`,
    `  --accent-foreground: ${color.accentForeground};`,
    `  --accent-muted: ${color.accentMuted};`,
    `  --accent-border: ${color.accentBorder};`,
    `  --success: ${color.success};`,
    `  --success-muted: ${color.successMuted};`,
    `  --success-border: ${color.successBorder};`,
    `  --info: ${color.info};`,
    `  --info-muted: ${color.infoMuted};`,
    `  --info-border: ${color.infoBorder};`,
    `  --warning: ${color.warning};`,
    `  --warning-muted: ${color.warningMuted};`,
    `  --warning-border: ${color.warningBorder};`,
    `  --neutral: ${color.neutral};`,
    `  --error: ${color.error};`,
    `  --error-muted: ${color.errorMuted};`,
    `  --error-border: ${color.errorBorder};`,
    `  --offline: ${color.offline};`,
    `  --font-sans: ${font.sans};`,
    `  --font-mono: ${font.mono};`,
    `  --radius-sm: ${radius.sm};`,
    `  --radius-md: ${radius.md};`,
    `  --radius-lg: ${radius.lg};`,
    `  --radius-xl: ${radius.xl};`,
    `  --radius-pill: ${radius.pill};`,
    `  --shadow-card: ${shadow.card};`,
    `  --shadow-overlay: ${shadow.overlay};`,
    `  --shadow-focus: ${shadow.focus};`,
    `  --transition-fast: ${motion.fast};`,
    `  --transition-standard: ${motion.standard};`,
    ...Object.entries(spacing).map(([key, value]) => `  --space-${key}: ${value};`),
  ].join('\n');
}
